#:schema https://www.schemastore.org/typst.json
[package]
name = "abdimasku-template"
version = "0.0.1"
compiler = "0.13.1"
entrypoint = "lib.typ"
authors = ["@stnDinus"]
description = "Abdimasku journal template. Dependent on https://github.com/stnDinus/typst-indonesian version 0.0.1 to be installed locally"
license = "GPL-3.0-only"
categories = ["paper", "layout"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
